/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package snakewithpartner.frames;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author trevornestman
 */
public class BoardFrame extends javax.swing.JFrame implements ActionListener{

    /**
     * Creates new form board
     */
    public BoardFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gameBoardPanal = new javax.swing.JPanel();
        boardTitlePanel = new javax.swing.JPanel();
        boardTitle = new javax.swing.JLabel();
        scoreTitle = new javax.swing.JLabel();
        playerScoreLabel = new javax.swing.JLabel();
        boardPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Snake");
        setAutoRequestFocus(false);
        setFocusable(false);
        setFocusableWindowState(false);
        setMaximumSize(new java.awt.Dimension(540, 640));
        setMinimumSize(new java.awt.Dimension(540, 640));
        setPreferredSize(new java.awt.Dimension(540, 640));
        setResizable(false);
        setSize(new java.awt.Dimension(540, 640));

        gameBoardPanal.setBackground(new java.awt.Color(0, 0, 0));
        gameBoardPanal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        boardTitlePanel.setBackground(new java.awt.Color(0, 0, 204));
        boardTitlePanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        boardTitle.setFont(new java.awt.Font("Noteworthy", 1, 48)); // NOI18N
        boardTitle.setForeground(new java.awt.Color(51, 255, 51));
        boardTitle.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        boardTitle.setText("SNAKE!");

        scoreTitle.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        scoreTitle.setForeground(new java.awt.Color(255, 102, 102));
        scoreTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        scoreTitle.setText("Score");

        playerScoreLabel.setFont(new java.awt.Font("SansSerif", 0, 36)); // NOI18N
        playerScoreLabel.setForeground(new java.awt.Color(255, 51, 102));
        playerScoreLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        playerScoreLabel.setText("0\n");

        javax.swing.GroupLayout boardTitlePanelLayout = new javax.swing.GroupLayout(boardTitlePanel);
        boardTitlePanel.setLayout(boardTitlePanelLayout);
        boardTitlePanelLayout.setHorizontalGroup(
            boardTitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(boardTitlePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(boardTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(boardTitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scoreTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                    .addComponent(playerScoreLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        boardTitlePanelLayout.setVerticalGroup(
            boardTitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(boardTitlePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(boardTitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(boardTitlePanelLayout.createSequentialGroup()
                        .addComponent(scoreTitle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(playerScoreLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(boardTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE))
                .addContainerGap())
        );

        boardPanel.setBackground(new java.awt.Color(0, 153, 0));

        javax.swing.GroupLayout boardPanelLayout = new javax.swing.GroupLayout(boardPanel);
        boardPanel.setLayout(boardPanelLayout);
        boardPanelLayout.setHorizontalGroup(
            boardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        boardPanelLayout.setVerticalGroup(
            boardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout gameBoardPanalLayout = new javax.swing.GroupLayout(gameBoardPanal);
        gameBoardPanal.setLayout(gameBoardPanalLayout);
        gameBoardPanalLayout.setHorizontalGroup(
            gameBoardPanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(boardTitlePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(gameBoardPanalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(boardPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        gameBoardPanalLayout.setVerticalGroup(
            gameBoardPanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gameBoardPanalLayout.createSequentialGroup()
                .addComponent(boardTitlePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(boardPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(gameBoardPanal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(gameBoardPanal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel boardPanel;
    private javax.swing.JLabel boardTitle;
    private javax.swing.JPanel boardTitlePanel;
    private javax.swing.JPanel gameBoardPanal;
    private javax.swing.JLabel playerScoreLabel;
    private javax.swing.JLabel scoreTitle;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
